### ISSUE TITLE
Role types derived from string array const

### ISSUE THREAD

**Issue by jotoh98** [ddddurk/ariatype#11]
Hi @durkdotdev, nice work!

I saw that the type definitions in the roles section and I was wondering if there's a reason that the array elements are duplicated in the type def.

I think you can reduce the code by asserting the arrays `as const` and retrieving the type by writing `type X = typeof array[number]`. You can find further information here.

Please let me know if I'm missing something or if that was helpful.

(A better explanation is [here](https://stackoverflow.com/questions/52085454/typescript-define-a-union-type-from-an-array-of-strings)).

Have a good one and thank you for contributing this package.

**Comment by ghost** [comment]
@jotoh98 Great catch, thank you! I've opened a PR to implement the `as const` typing for the roles. Feel free to take a look
